# Generated by Django 2.2 on 2019-12-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationName', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('IAGACode', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('Latitude', models.FloatField(blank=True, default=None, null=True)),
                ('Longitude', models.FloatField(blank=True, default=None, null=True)),
                ('Elevation', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IAGACode', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('DateTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('DOY', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('X', models.FloatField(blank=True, default=None, null=True)),
                ('Y', models.FloatField(blank=True, default=None, null=True)),
                ('Z', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
