# Generated by Django 2.2 on 2020-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsdata',
            name='Beta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
