# Generated by Django 2.2 on 2020-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_stationsdata_beta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationsdata',
            name='Beta',
        ),
        migrations.AddField(
            model_name='station',
            name='Beta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
