# Generated by Django 2.2 on 2020-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20200113_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='Beta',
            new_name='BetaX',
        ),
        migrations.AddField(
            model_name='station',
            name='BetaY',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='BetaZ',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
